function [fitresult, gof] = CreateFit(t, FracCover)
%CREATEFIT(T,FRACCOVER)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t
%      Y Output: FracCover
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Dec-2020 16:13:46


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t, FracCover );

% Set up fittype and options.
ft = fittype( 'A*(1-exp(-k*x))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.231817456501529 0.545052545191676];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'FracCover vs. t', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
% xlabel( 't', 'Interpreter', 'none' );
% ylabel( 'FracCover', 'Interpreter', 'none' );
% grid on


